resources__host_files:
  - dest: '/etc/docker/daemon.json'
    content: |
      {
        "bip": "192.168.63.1/24",
        "live-restore": true
      }
  - dest: '/etc/resolv.conf'
    content: |
      nameserver 10.233.0.3
      nameserver 8.8.8.8
    mode: '0644'
